### ISSUE TITLE
Fatal error: 'clamav.h' file not found

### ISSUE THREAD

**Issue by mjlescano** [srijs/node-clam-engine#4]
Hi @srijs !

I'm using node `6.12` on MacOS, and installed clamav using `brew install clamav`, and when trying to `npm install --save clam-engine` it throws `../engine.cc:3:10: fatal error: 'clamav.h' file not found`.

Is there a way to specify the location of my clamscan install path, or maybe I'm missing something else?

Full log:
```
$ npm i --save clam-engine

> clam-engine@2.0.1 install /Users/tout/Sites/tactivos/antivirus/node_modules/clam-engine
> node-gyp rebuild

  CXX(target) Release/obj.target/engine/engine.o
../engine.cc:3:10: fatal error: 'clamav.h' file not found
#include <clamav.h>
         ^~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/engine/engine.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ./node_modules/clam-engine
gyp ERR! node -v v6.12.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN antivirus@1.0.0 No description
npm WARN antivirus@1.0.0 No repository field.
npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save" "clam-engine"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! clam-engine@2.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the clam-engine@2.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the clam-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs clam-engine
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls clam-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!  ./npm-debug.log
```

**Comment by srijs** [comment]
Hi @mjlescano, thanks for the report!

That looks like `brew` might not be installing the header files to a place where they can be found by node.

Would you mind telling me what version of OS X and brew you're using? Also, if there's any way that you could find out where brew might've installed those files (`brew --prefix` should tell you), that would be very useful to know!

**Comment by mjlescano** [comment]
Here's goes my versions, and some more data just in case :)

macOS -> `10.13.2`
`brew --prefix` -> `/usr/local`
`which clamscan` -> `/usr/local/bin/clamscan`
`which node` -> `/Users/tout/n/bin/node`

And with `find /usr/local/**/clamav.h` it gives me:
```
/usr/local/Cellar/clamav/0.99.2_1/include/clamav.h
/usr/local/include/clamav.h
```

**Comment by srijs** [comment]
Okay, so this might be a search-path issue, however I'll only get to testing this next week when I have access to an OS X machine.

In the meantime, it appears that the default clang shipped with High Sierra doesn't search `/usr/local/` properly unless you install the version of clang bundled with the Xcode Command Line tools, like so:

```
xcode-select --install
```

If you want, go ahead and give this a shot!
